---
# curl -k -H "Content-Type: application/json" -X POST https://172.28.128.4/api/v1/webhooks/add_link -H "St2-Api-Key: MmU2MTA4MzE3N2FkZWNiNDgzZmE0NjNmODA4OGVjZWI3ODZmMTliYTJlNjUzMjEwNGQ4ODUzYTM0Mzk3ZGZjYQ" --data '{"left": "eos.spine1:eth4", "right": "eos.spine2:eth4"}'

name: add_link
description: Webhook to allow adding a link.
pack: chatops_demo
criteria: {}
enabled: true
trigger:
    type: "core.st2.webhook"
    parameters:
        url: "add_link"
action:
  ref: chatops_demo.add_link
  parameters:
    left: '{{trigger.body.left}}'
    right: '{{trigger.body.right}}'
