---
# curl -k -H "Content-Type: application/json" -X POST https://172.28.128.3/api/v1/webhooks/deploy_fabric -H "St2-Api-Key: NmYyZWVmNmYxYmZhNzE4Y2QyZmMwNTM3NzRmNDNkNWVhZmQ1YWQzNTliZTk5NDEwYzYwNTQ1M2NmMWI0YmMxNg" --data '{}'
name: deploy_fabric
description: Webhook to allow deploying the fabric.
pack: chatops_demo
criteria: {}
enabled: true
trigger:
    type: "core.st2.webhook"
    parameters:
        url: "deploy_fabric"
action:
  ref: chatops_demo.deploy_fabric_with_confirm_api
